<?php
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 *
 * @file
 * Primary module hooks for Hbk Cforge module.
 */
function hbk_popin_theme($existing, $type, $theme, $path) {
  $hooks['hbk_popin_block'] = [
    'variables' => [
      'popin' => null,
      'attributes' => NULL
    ]
  ];
  $hooks['hbk_popin_whatsappmessage'] = [
    'variables' => [
      'popin_content' => null,
      'popin_placeholder' => null,
      'popin_titre' => null,
      'phone_number' => null,
      'attributes' => NULL,
      'popin_send_email' => null
    ]
  ];
  $hooks['hbk_popin_whatsapp_message'] = [
    'render element' => 'elements'
  ];
  return $hooks;
}

/**
 * Prepares variables for whatsapp_message templates.
 *
 * Default template: hbk-popin-whatsapp-message.html.twig.
 *
 * @param array $variables
 *        An associative array containing:
 *        - elements: An associative array containing the whatsapp_message
 *        information and any
 *        fields attached to the entity.
 *        - attributes: HTML attributes for the containing element.
 */
function template_preprocess_hbk_popin_whatsapp_message(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function hbk_popin_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish whatsapp_messages.
      $storage = \Drupal::entityTypeManager()->getStorage('hbk_popin_whatsapp_message');
      $hbk_popin_whatsapp_message_ids = $storage->getQuery()->condition('uid', $account->id())->condition('status', 1)->accessCheck(FALSE)->execute();
      foreach ($storage->loadMultiple($hbk_popin_whatsapp_message_ids) as $hbk_popin_whatsapp_message) {
        $hbk_popin_whatsapp_message->set('status', FALSE)->save();
      }
      break;
    
    case 'user_cancel_reassign':
      // Anonymize whatsapp_messages.
      $storage = \Drupal::entityTypeManager()->getStorage('hbk_popin_whatsapp_message');
      $hbk_popin_whatsapp_message_ids = $storage->getQuery()->condition('uid', $account->id())->accessCheck(FALSE)->execute();
      foreach ($storage->loadMultiple($hbk_popin_whatsapp_message_ids) as $hbk_popin_whatsapp_message) {
        $hbk_popin_whatsapp_message->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function hbk_popin_user_predelete(UserInterface $account): void {
  // Delete whatsapp_messages that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('hbk_popin_whatsapp_message');
  $hbk_popin_whatsapp_message_ids = $storage->getQuery()->condition('uid', $account->id())->accessCheck(FALSE)->execute();
  $storage->delete($storage->loadMultiple($hbk_popin_whatsapp_message_ids));
}
