<?php

/**
 *
 * @file
 * Primary module hooks for Hbk Cforge module.
 */
function hbk_popin_theme($existing, $type, $theme, $path) {
  $hooks['hbk_popin_block'] = [
    'variables' => [
      'popin' => null,
      'attributes' => NULL
    ]
  ];
  $hooks['hbk_popin_whatsappmessage'] = [
    'variables' => [
      'popin_content' => null,
      'popin_placeholder' => null,
      'popin_titre' => null,
      'phone_number' => null,
      'attributes' => NULL,
      'popin_send_email' => null
    ]
  ];
  return $hooks;
}

