block.settings.hbk_popin:
  type: block_settings
  label: "Popin block"
  mapping:
    example:
      type: string
      label: Example

block.settings.hbk_popin_popup:
  type: block_settings
  label: 'HBK Popin - Popup WhatsApp block settings'
  mapping:
    message:
      type: text
      label: 'Message'
      translatable: true
    placeholder:
      type: label
      label: 'Placeholder'
      translatable: true
    titre:
      type: label
      label: 'Titre'
      translatable: true
    phone_number:
      type: string
      label: 'Phone number'
      translatable: false
    send_email:
      type: email
      label: 'Send copy to'
      translatable: false
    class_container:
      type: string
      label: 'Container classes'
      translatable: false